name: check-docker-tag
description: Checks if a Docker image tag exists on Docker Hub.

inputs:
    image:
        description: 'Docker image name (e.g. myrepo/myimage)'
        required: true
        type: string
    tag:
        description: 'Docker tag to check'
        required: true
        type: string

outputs:
    is_available:
        description: 'Returns true if the Docker tag does NOT exist'
        value: ${{ steps.check-tag.outputs.is_available }}

runs:
    using: 'composite'
    steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Check if Docker tag exists
          id: check-tag
          shell: bash
          run: |
              image="${{ inputs.image }}"
              tag="${{ inputs.tag }}"

              if [ -z "$image" ] || [ -z "$tag" ]; then
                echo "is_available=false" >> "$GITHUB_OUTPUT"
                echo "Missing image or tag input"
                exit 1
              fi

              if docker manifest inspect "$image:$tag" > /dev/null 2>&1; then
                echo "Tag exists ✅"
                echo "is_available=false" >> "$GITHUB_OUTPUT"
                exit 1
              fi

              echo "Tag does not exist ❌"
              echo "is_available=true" >> "$GITHUB_OUTPUT"
