name: 'run-pytest'
description: 'Set up Python, install dependencies, and run pytest'
inputs:
    python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'

runs:
    using: 'composite'
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v4
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install pip
          shell: bash
          run: python -m pip install --upgrade pip

        - name: Install dependencies
          shell: bash
          run: pip install -r 'requirements.txt'

        - name: Install dev dependencies
          shell: bash
          run: pip install -r 'requirements-dev.txt'

        - name: Run tests
          shell: bash
          run: pytest
